import { ClientMaritalStatus } from './client-marital-status.type';
import { ClientReligion } from './client-religion.types';
import { ClientStatus } from './client-status.type';
import { LivingArrangements } from './living-arrangements.type';
import { TypeOfGuardianship } from './type-of-guardianship.type';
import { UserGender } from './user-gender.type';
import { WealthStatus } from './wealth-status.type';

export type Client = {
  _id: string;
  guardianId: string;
  gender: UserGender;
  title?: string;
  firstname: string;
  lastname: string;
  birthday: Date;
  deathday?: Date;
  avatar?: string;
  localCourt?: string;
  caseNumber?: string;
  scopeOfDuties?: string[];
  guardianshipStartedAt: Date;
  guardianshipEndedAt?: Date;
  livingArrangement?: LivingArrangements;
  wealthStatus?: WealthStatus;
  typeOfGuardianship?: TypeOfGuardianship;
  isGuardianshipTakenOver: boolean;
  prevGuardianType?: string;
  prevGuardianshipStartedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  status: ClientStatus;
  maritalStatus?: ClientMaritalStatus;
  maritalStatusStartedAt?: Date;
  numberOfChildren?: number;
  isSingleParent?: boolean;
  birthname?: string;
  citizenship?: string;
  additionalCitizenship?: string;
  countryOfBirth?: string;
  cityOfBirth?: string;
  religion?: ClientReligion;
  taxId?: string;
  street?: string;
  streetNo?: string;
  postalCode?: string;
  city?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  fax?: string;
  isAlternativeAddressActive?: boolean;
  alternativeStreet?: string;
  alternativeStreetNo?: string;
  alternativePostalCode?: string;
  alternativeCity?: string;
};
