import { CreatableSelectOption } from '@/components/ui/creatable-select';

export const LOCAL_COURTS_OPTIONS: CreatableSelectOption[] = [
  { value: 'Weimar', label: 'Weimar' },
  { value: 'Stadtroda', label: 'Stadtroda' },
  { value: 'Sonneberg', label: 'Sonneberg' },
  { value: 'Sömmerda', label: 'Sömmerda' },
  { value: 'Pößneck', label: 'Pößneck' },
  { value: 'Meiningen', label: 'Meiningen' },
  { value: 'Heilbad Heiligenstadt', label: 'Heilbad Heiligenstadt' },
  { value: 'Erfurt', label: 'Erfurt' },
  { value: 'Bad Salzungen', label: 'Bad Salzungen' },
  { value: 'Arnstadt Zweigstelle Ilmenau', label: 'Arnstadt Zweigstelle Ilmenau' },
  { value: 'Zeitz', label: 'Zeitz' },
  { value: 'Sangerhausen', label: 'Sangerhausen' },
  { value: 'Salzwedel', label: 'Salzwedel' },
  { value: 'Quedlinburg', label: 'Quedlinburg' },
  { value: 'Köthen', label: 'Köthen' },
  { value: 'Halle (Saale)', label: 'Halle (Saale)' },
  { value: 'Haldensleben', label: 'Haldensleben' },
  { value: 'Dessau-Roßlau', label: 'Dessau-Roßlau' },
  { value: 'Bitterfeld-Wolfen', label: 'Bitterfeld-Wolfen' },
  { value: 'Bernburg', label: 'Bernburg' },
  { value: 'Zittau Zweigstelle Löbau', label: 'Zittau Zweigstelle Löbau' },
  { value: 'Zittau', label: 'Zittau' },
  { value: 'Torgau Zweigstelle Oschatz', label: 'Torgau Zweigstelle Oschatz' },
  { value: 'Meißen', label: 'Meißen' },
  { value: 'Hohenstein-Ernstthal', label: 'Hohenstein-Ernstthal' },
  { value: 'Grimma', label: 'Grimma' },
  { value: 'Freiberg', label: 'Freiberg' },
  { value: 'Eilenburg', label: 'Eilenburg' },
  { value: 'Chemnitz', label: 'Chemnitz' },
  { value: 'Borna', label: 'Borna' },
  { value: 'Wismar', label: 'Wismar' },
  {
    value: 'Waren (Müritz) Zweigstelle Neustrelitz',
    label: 'Waren (Müritz) Zweigstelle Neustrelitz',
  },
  { value: 'Rostock', label: 'Rostock' },
  { value: 'Neubrandenburg Zweigstelle Demmin', label: 'Neubrandenburg Zweigstelle Demmin' },
  { value: 'Neubrandenburg', label: 'Neubrandenburg' },
  { value: 'Ludwigslust', label: 'Ludwigslust' },
  { value: 'Greifswald', label: 'Greifswald' },
  { value: 'Zehdenick', label: 'Zehdenick' },
  { value: 'Luckenwalde', label: 'Luckenwalde' },
  { value: 'Königs Wusterhausen', label: 'Königs Wusterhausen' },
  { value: 'Fürstenwalde/Spree', label: 'Fürstenwalde/Spree' },
  { value: 'Frankfurt (Oder)', label: 'Frankfurt (Oder)' },
  { value: 'Bernau bei Berlin', label: 'Bernau bei Berlin' },
  { value: 'Bad Freienwalde (Oder)', label: 'Bad Freienwalde (Oder)' },
  {
    value: 'Tempelhof-Kreuzberg - Familiengericht -',
    label: 'Tempelhof-Kreuzberg - Familiengericht -',
  },
  { value: 'Pankow/Weißensee', label: 'Pankow/Weißensee' },
  { value: 'Neukölln', label: 'Neukölln' },
  { value: 'Lichtenberg', label: 'Lichtenberg' },
  { value: 'Saarbrücken', label: 'Saarbrücken' },
  { value: 'Merzig', label: 'Merzig' },
  { value: 'Würzburg', label: 'Würzburg' },
  { value: 'Weißenburg', label: 'Weißenburg' },
  { value: 'Weilheim i.OB', label: 'Weilheim i.OB' },
  { value: 'Weiden i.d. OPf.', label: 'Weiden i.d. OPf.' },
  { value: 'Viechtach', label: 'Viechtach' },
  { value: 'Tirschenreuth', label: 'Tirschenreuth' },
  { value: 'Straubing', label: 'Straubing' },
  { value: 'Schwabach', label: 'Schwabach' },
  { value: 'Pfaffenhofen a.d.Ilm', label: 'Pfaffenhofen a.d.Ilm' },
  { value: 'Nördlingen', label: 'Nördlingen' },
  { value: 'Neuburg a. d. Donau', label: 'Neuburg a. d. Donau' },
  { value: 'München', label: 'München' },
  { value: 'Miesbach', label: 'Miesbach' },
  { value: 'Lindau (Bodensee)', label: 'Lindau (Bodensee)' },
  { value: 'Kronach', label: 'Kronach' },
  { value: 'Kelheim', label: 'Kelheim' },
  { value: 'Kaufbeuren', label: 'Kaufbeuren' },
  { value: 'Garmisch-Partenkirchen', label: 'Garmisch-Partenkirchen' },
  { value: 'Forchheim', label: 'Forchheim' },
  { value: 'Erlangen', label: 'Erlangen' },
  { value: 'Ebersberg', label: 'Ebersberg' },
  { value: 'Deggendorf', label: 'Deggendorf' },
  { value: 'Dachau', label: 'Dachau' },
  { value: 'Coburg', label: 'Coburg' },
  {
    value: 'Aschaffenburg Zweigstelle Alzenau in Unterfranken',
    label: 'Aschaffenburg Zweigstelle Alzenau in Unterfranken',
  },
  { value: 'Aschaffenburg', label: 'Aschaffenburg' },
  { value: 'Aichach', label: 'Aichach' },
  { value: 'Weinheim', label: 'Weinheim' },
  { value: 'Waldshut-Tiengen', label: 'Waldshut-Tiengen' },
  { value: 'Villingen-Schwenningen', label: 'Villingen-Schwenningen' },
  { value: 'Vaihingen an der Enz', label: 'Vaihingen an der Enz' },
  { value: 'Überlingen', label: 'Überlingen' },
  { value: 'Tübingen', label: 'Tübingen' },
  { value: 'Titisee-Neustadt', label: 'Titisee-Neustadt' },
  { value: 'Stockach', label: 'Stockach' },
  { value: 'Spaichingen', label: 'Spaichingen' },
  { value: 'Sinsheim', label: 'Sinsheim' },
  { value: 'Singen am Hohentwiel', label: 'Singen am Hohentwiel' },
  { value: 'Schwetzingen', label: 'Schwetzingen' },
  { value: 'Sankt Blasien', label: 'Sankt Blasien' },
  { value: 'Philippsburg', label: 'Philippsburg' },
  { value: 'Pforzheim', label: 'Pforzheim' },
  { value: 'Offenburg', label: 'Offenburg' },
  { value: 'Oberkirch', label: 'Oberkirch' },
  { value: 'Marbach', label: 'Marbach' },
  { value: 'Künzelsau', label: 'Künzelsau' },
  { value: 'Kenzingen', label: 'Kenzingen' },
  { value: 'Karlsruhe', label: 'Karlsruhe' },
  { value: 'Horb am Neckar', label: 'Horb am Neckar' },
  { value: 'Heidenheim a. d. Brenz', label: 'Heidenheim a. d. Brenz' },
  { value: 'Geislingen/Steige', label: 'Geislingen/Steige' },
  { value: 'Freudenstadt', label: 'Freudenstadt' },
  { value: 'Ettlingen', label: 'Ettlingen' },
  { value: 'Emmendingen', label: 'Emmendingen' },
  { value: 'Calw', label: 'Calw' },
  { value: 'Breisach am Rhein', label: 'Breisach am Rhein' },
  { value: 'Besigheim', label: 'Besigheim' },
  { value: 'Bad Mergentheim', label: 'Bad Mergentheim' },
  { value: 'Aalen', label: 'Aalen' },
  { value: 'Wittlich', label: 'Wittlich' },
  { value: 'Saarburg', label: 'Saarburg' },
  { value: 'Rockenhausen', label: 'Rockenhausen' },
  { value: 'Mainz', label: 'Mainz' },
  { value: 'Landstuhl', label: 'Landstuhl' },
  { value: 'Koblenz', label: 'Koblenz' },
  { value: 'Kandel', label: 'Kandel' },
  { value: 'Kaiserslautern', label: 'Kaiserslautern' },
  { value: 'Hermeskeil', label: 'Hermeskeil' },
  { value: 'Germersheim', label: 'Germersheim' },
  { value: 'Diez', label: 'Diez' },
  { value: 'Daun', label: 'Daun' },
  { value: 'Cochem', label: 'Cochem' },
  { value: 'Betzdorf', label: 'Betzdorf' },
  { value: 'Bad Sobernheim', label: 'Bad Sobernheim' },
  { value: 'Bad Neuenahr-Ahrweiler', label: 'Bad Neuenahr-Ahrweiler' },
  { value: 'Bad Dürkheim', label: 'Bad Dürkheim' },
  { value: 'Weilburg', label: 'Weilburg' },
  { value: 'Seligenstadt', label: 'Seligenstadt' },
  { value: 'Schwalmstadt', label: 'Schwalmstadt' },
  { value: 'Michelstadt', label: 'Michelstadt' },
  { value: 'Melsungen', label: 'Melsungen' },
  { value: 'Limburg a. d. Lahn', label: 'Limburg a. d. Lahn' },
  { value: 'Korbach', label: 'Korbach' },
  { value: 'Kirchhain', label: 'Kirchhain' },
  { value: 'Hünfeld', label: 'Hünfeld' },
  { value: 'Friedberg (Hessen)', label: 'Friedberg (Hessen)' },
  { value: 'Dillenburg Zweigstelle Herborn', label: 'Dillenburg Zweigstelle Herborn' },
  { value: 'Dillenburg', label: 'Dillenburg' },
  { value: 'Dieburg', label: 'Dieburg' },
  { value: 'Büdingen', label: 'Büdingen' },
  { value: 'Bad Schwalbach', label: 'Bad Schwalbach' },
  { value: 'Bad Homburg', label: 'Bad Homburg' },
  { value: 'Wesel', label: 'Wesel' },
  { value: 'Warstein', label: 'Warstein' },
  { value: 'Warendorf', label: 'Warendorf' },
  { value: 'Waldbröl', label: 'Waldbröl' },
  { value: 'Unna', label: 'Unna' },
  { value: 'Schmallenberg', label: 'Schmallenberg' },
  { value: 'Schleiden', label: 'Schleiden' },
  { value: 'Rheinbach', label: 'Rheinbach' },
  { value: 'Rheda-Wiedenbrück', label: 'Rheda-Wiedenbrück' },
  { value: 'Ratingen', label: 'Ratingen' },
  { value: 'Paderborn', label: 'Paderborn' },
  { value: 'Neuss', label: 'Neuss' },
  { value: 'Monschau', label: 'Monschau' },
  { value: 'Moers', label: 'Moers' },
  { value: 'Minden', label: 'Minden' },
  { value: 'Meschede', label: 'Meschede' },
  { value: 'Marsberg', label: 'Marsberg' },
  { value: 'Lünen', label: 'Lünen' },
  { value: 'Langenfeld (Rheinland)', label: 'Langenfeld (Rheinland)' },
  { value: 'Krefeld', label: 'Krefeld' },
  { value: 'Kleve', label: 'Kleve' },
  { value: 'Ibbenbüren', label: 'Ibbenbüren' },
  { value: 'Herford', label: 'Herford' },
  { value: 'Hamm', label: 'Hamm' },
  { value: 'Hagen', label: 'Hagen' },
  { value: 'Gummersbach', label: 'Gummersbach' },
  { value: 'Euskirchen', label: 'Euskirchen' },
  { value: 'Essen-Borbeck', label: 'Essen-Borbeck' },
  { value: 'Essen', label: 'Essen' },
  { value: 'Eschweiler', label: 'Eschweiler' },
  { value: 'Erkelenz', label: 'Erkelenz' },
  { value: 'Duisburg-Ruhrort', label: 'Duisburg-Ruhrort' },
  { value: 'Dinslaken', label: 'Dinslaken' },
  { value: 'Delbrück', label: 'Delbrück' },
  { value: 'Coesfeld', label: 'Coesfeld' },
  { value: 'Castrop-Rauxel', label: 'Castrop-Rauxel' },
  { value: 'Brilon', label: 'Brilon' },
  { value: 'Brakel', label: 'Brakel' },
  { value: 'Bottrop', label: 'Bottrop' },
  { value: 'Bochum', label: 'Bochum' },
  { value: 'Bielefeld', label: 'Bielefeld' },
  { value: 'Bad Oeynhausen', label: 'Bad Oeynhausen' },
  { value: 'Ahaus', label: 'Ahaus' },
  { value: 'Bremerhaven', label: 'Bremerhaven' },
  { value: 'Wolfsburg', label: 'Wolfsburg' },
  { value: 'Walsrode', label: 'Walsrode' },
  { value: 'Verden (Aller)', label: 'Verden (Aller)' },
  { value: 'Varel', label: 'Varel' },
  { value: 'Stadthagen', label: 'Stadthagen' },
  { value: 'Stade', label: 'Stade' },
  { value: 'Soltau', label: 'Soltau' },
  { value: 'Rinteln', label: 'Rinteln' },
  { value: 'Northeim', label: 'Northeim' },
  { value: 'Nordenham', label: 'Nordenham' },
  { value: 'Norden', label: 'Norden' },
  { value: 'Meppen', label: 'Meppen' },
  { value: 'Lüneburg', label: 'Lüneburg' },
  { value: 'Leer (Ostfriesland)', label: 'Leer (Ostfriesland)' },
  { value: 'Jever', label: 'Jever' },
  { value: 'Holzminden', label: 'Holzminden' },
  { value: 'Herzberg am Harz', label: 'Herzberg am Harz' },
  { value: 'Hannover', label: 'Hannover' },
  { value: 'Diepholz', label: 'Diepholz' },
  { value: 'Cloppenburg', label: 'Cloppenburg' },
  { value: 'Celle', label: 'Celle' },
  { value: 'Burgwedel', label: 'Burgwedel' },
  { value: 'Brake (Unterweser)', label: 'Brake (Unterweser)' },
  { value: 'Bersenbrück', label: 'Bersenbrück' },
  { value: 'Hamburg-St.Georg', label: 'Hamburg-St.Georg' },
  { value: 'Hamburg', label: 'Hamburg' },
  { value: 'Rendsburg', label: 'Rendsburg' },
  { value: 'Reinbek', label: 'Reinbek' },
  { value: 'Plön', label: 'Plön' },
  { value: 'Pinneberg', label: 'Pinneberg' },
  { value: 'Niebüll', label: 'Niebüll' },
  { value: 'Kiel', label: 'Kiel' },
  { value: 'Elmshorn', label: 'Elmshorn' },
  { value: 'Ahrensburg', label: 'Ahrensburg' },
  { value: 'Sondershausen', label: 'Sondershausen' },
  { value: 'Rudolstadt', label: 'Rudolstadt' },
  { value: 'Nordhausen', label: 'Nordhausen' },
  { value: 'Mühlhausen', label: 'Mühlhausen' },
  { value: 'Jena', label: 'Jena' },
  { value: 'Greiz', label: 'Greiz' },
  { value: 'Gera', label: 'Gera' },
  { value: 'Arnstadt', label: 'Arnstadt' },
  { value: 'Altenburg', label: 'Altenburg' },
  { value: 'Zerbst', label: 'Zerbst' },
  { value: 'Weißenfels', label: 'Weißenfels' },
  { value: 'Oschersleben', label: 'Oschersleben' },
  { value: 'Merseburg', label: 'Merseburg' },
  { value: 'Magdeburg', label: 'Magdeburg' },
  { value: 'Gardelegen', label: 'Gardelegen' },
  { value: 'Aschersleben', label: 'Aschersleben' },
  { value: 'Zwickau', label: 'Zwickau' },
  { value: 'Plauen', label: 'Plauen' },
  { value: 'Pirna', label: 'Pirna' },
  { value: 'Leipzig', label: 'Leipzig' },
  { value: 'Hoyerswerda', label: 'Hoyerswerda' },
  { value: 'Dresden', label: 'Dresden' },
  {
    value: 'Aue-Bad Schlema Zweigstelle Stollberg',
    label: 'Aue-Bad Schlema Zweigstelle Stollberg',
  },
  { value: 'Wismar Zweigstelle Grevesmühlen', label: 'Wismar Zweigstelle Grevesmühlen' },
  { value: 'Waren (Müritz)', label: 'Waren (Müritz)' },
  { value: 'Pasewalk Zweigstelle Anklam', label: 'Pasewalk Zweigstelle Anklam' },
  { value: 'Pasewalk', label: 'Pasewalk' },
  { value: 'Zossen', label: 'Zossen' },
  { value: 'Senftenberg', label: 'Senftenberg' },
  { value: 'Prenzlau', label: 'Prenzlau' },
  { value: 'Potsdam', label: 'Potsdam' },
  { value: 'Perleberg', label: 'Perleberg' },
  { value: 'Neuruppin', label: 'Neuruppin' },
  { value: 'Lübben (Spreewald)', label: 'Lübben (Spreewald)' },
  { value: 'Eisenhüttenstadt', label: 'Eisenhüttenstadt' },
  { value: 'Cottbus', label: 'Cottbus' },
  { value: 'Bad Liebenwerda', label: 'Bad Liebenwerda' },
  { value: 'Spandau', label: 'Spandau' },
  { value: 'Mitte', label: 'Mitte' },
  { value: 'Köpenick', label: 'Köpenick' },
  { value: 'Völklingen', label: 'Völklingen' },
  { value: 'St. Wendel', label: 'St. Wendel' },
  { value: 'Sankt Ingbert', label: 'Sankt Ingbert' },
  { value: 'Saarlouis', label: 'Saarlouis' },
  { value: 'Ottweiler', label: 'Ottweiler' },
  { value: 'Lebach', label: 'Lebach' },
  { value: 'Homburg', label: 'Homburg' },
  { value: 'Wolfratshausen', label: 'Wolfratshausen' },
  { value: 'Sonthofen', label: 'Sonthofen' },
  { value: 'Schweinfurt', label: 'Schweinfurt' },
  { value: 'Rosenheim', label: 'Rosenheim' },
  { value: 'Regensburg', label: 'Regensburg' },
  { value: 'Passau', label: 'Passau' },
  { value: 'Neustadt an der Aisch', label: 'Neustadt an der Aisch' },
  { value: 'Memmingen', label: 'Memmingen' },
  { value: 'Lichtenfels', label: 'Lichtenfels' },
  { value: 'Kitzingen', label: 'Kitzingen' },
  { value: 'Kempten (Allgäu)', label: 'Kempten (Allgäu)' },
  { value: 'Hof', label: 'Hof' },
  { value: 'Hersbruck', label: 'Hersbruck' },
  { value: 'Haßfurt', label: 'Haßfurt' },
  { value: 'Günzburg', label: 'Günzburg' },
  { value: 'Gemünden am Main', label: 'Gemünden am Main' },
  { value: 'Fürth', label: 'Fürth' },
  { value: 'Freyung', label: 'Freyung' },
  { value: 'Erding', label: 'Erding' },
  { value: 'Eggenfelden', label: 'Eggenfelden' },
  { value: 'Bad Neustadt a.d. Saale', label: 'Bad Neustadt a.d. Saale' },
  { value: 'Bad Kissingen', label: 'Bad Kissingen' },
  { value: 'Ansbach', label: 'Ansbach' },
  { value: 'Amberg', label: 'Amberg' },
  { value: 'Altötting', label: 'Altötting' },
  { value: 'Wolfach', label: 'Wolfach' },
  { value: 'Wiesloch', label: 'Wiesloch' },
  { value: 'Waldkirch', label: 'Waldkirch' },
  { value: 'Waiblingen', label: 'Waiblingen' },
  { value: 'Tettnang', label: 'Tettnang' },
  { value: 'Tauberbischofsheim', label: 'Tauberbischofsheim' },
  { value: 'Stuttgart-Bad Cannstatt', label: 'Stuttgart-Bad Cannstatt' },
  { value: 'Stuttgart', label: 'Stuttgart' },
  { value: 'Staufen im Breisgau', label: 'Staufen im Breisgau' },
  { value: 'Sigmaringen', label: 'Sigmaringen' },
  { value: 'Schwäbisch Hall', label: 'Schwäbisch Hall' },
  { value: 'Schwäbisch Gmünd', label: 'Schwäbisch Gmünd' },
  { value: 'Schorndorf', label: 'Schorndorf' },
  { value: 'Schönau im Schwarzwald', label: 'Schönau im Schwarzwald' },
  { value: 'Rottweil', label: 'Rottweil' },
  { value: 'Rastatt', label: 'Rastatt' },
  { value: 'Öhringen', label: 'Öhringen' },
  { value: 'Münsingen', label: 'Münsingen' },
  { value: 'Müllheim', label: 'Müllheim' },
  { value: 'Mosbach', label: 'Mosbach' },
  { value: 'Leonberg', label: 'Leonberg' },
  { value: 'Lahr/Schwarzwald', label: 'Lahr/Schwarzwald' },
  { value: 'Kirchheim unter Teck', label: 'Kirchheim unter Teck' },
  { value: 'Kehl', label: 'Kehl' },
  { value: 'Karlsruhe-Durlach', label: 'Karlsruhe-Durlach' },
  { value: 'Hechingen', label: 'Hechingen' },
  { value: 'Freiburg im Breisgau', label: 'Freiburg im Breisgau' },
  { value: 'Esslingen am Neckar', label: 'Esslingen am Neckar' },
  { value: 'Ehingen/Donau', label: 'Ehingen/Donau' },
  { value: 'Crailsheim', label: 'Crailsheim' },
  { value: 'Bühl', label: 'Bühl' },
  { value: 'Böblingen', label: 'Böblingen' },
  { value: 'Biberach/Riß', label: 'Biberach/Riß' },
  { value: 'Balingen', label: 'Balingen' },
  { value: 'Bad Urach', label: 'Bad Urach' },
  { value: 'Bad Säckingen', label: 'Bad Säckingen' },
  { value: 'Backnang', label: 'Backnang' },
  { value: 'Adelsheim', label: 'Adelsheim' },
  { value: 'Worms', label: 'Worms' },
  { value: 'Trier', label: 'Trier' },
  { value: 'Sinzig', label: 'Sinzig' },
  { value: 'Simmern (Hunsrück)', label: 'Simmern (Hunsrück)' },
  { value: 'Sankt Goar', label: 'Sankt Goar' },
  { value: 'Prüm', label: 'Prüm' },
  { value: 'Mayen', label: 'Mayen' },
  { value: 'Linz am Rhein', label: 'Linz am Rhein' },
  {
    value: 'Landau in der Pfalz Zweigstelle Bad Bergzabern',
    label: 'Landau in der Pfalz Zweigstelle Bad Bergzabern',
  },
  { value: 'Bitburg', label: 'Bitburg' },
  { value: 'Bingen am Rhein', label: 'Bingen am Rhein' },
  { value: 'Bernkastel-Kues', label: 'Bernkastel-Kues' },
  { value: 'Andernach', label: 'Andernach' },
  { value: 'Alzey', label: 'Alzey' },
  { value: 'Altenkirchen (Westerwald)', label: 'Altenkirchen (Westerwald)' },
  { value: 'Marburg', label: 'Marburg' },
  {
    value: 'Limburg a. d. Lahn Zweigstelle Hadamar',
    label: 'Limburg a. d. Lahn Zweigstelle Hadamar',
  },
  { value: 'Langen (Hessen)', label: 'Langen (Hessen)' },
  { value: 'Königstein im Taunus', label: 'Königstein im Taunus' },
  { value: 'Kassel Zweigstelle Hofgeismar', label: 'Kassel Zweigstelle Hofgeismar' },
  { value: 'Hanau', label: 'Hanau' },
  { value: 'Groß-Gerau', label: 'Groß-Gerau' },
  { value: 'Gießen', label: 'Gießen' },
  { value: 'Gelnhausen', label: 'Gelnhausen' },
  { value: 'Fulda', label: 'Fulda' },
  { value: 'Frankenberg (Eder)', label: 'Frankenberg (Eder)' },
  { value: 'Bad Hersfeld', label: 'Bad Hersfeld' },
  { value: 'Wuppertal', label: 'Wuppertal' },
  { value: 'Wetter (Ruhr)', label: 'Wetter (Ruhr)' },
  { value: 'Wermelskirchen', label: 'Wermelskirchen' },
  { value: 'Solingen', label: 'Solingen' },
  { value: 'Schwerte', label: 'Schwerte' },
  { value: 'Schwelm', label: 'Schwelm' },
  { value: 'Rheine', label: 'Rheine' },
  { value: 'Remscheid', label: 'Remscheid' },
  { value: 'Olpe', label: 'Olpe' },
  { value: 'Mülheim an der Ruhr', label: 'Mülheim an der Ruhr' },
  { value: 'Mönchengladbach-Rheydt', label: 'Mönchengladbach-Rheydt' },
  { value: 'Mönchengladbach', label: 'Mönchengladbach' },
  { value: 'Mettmann', label: 'Mettmann' },
  { value: 'Menden (Sauerland)', label: 'Menden (Sauerland)' },
  { value: 'Meinerzhagen', label: 'Meinerzhagen' },
  { value: 'Lüdinghausen', label: 'Lüdinghausen' },
  { value: 'Lüdenscheid', label: 'Lüdenscheid' },
  { value: 'Lippstadt', label: 'Lippstadt' },
  { value: 'Lemgo', label: 'Lemgo' },
  { value: 'Königswinter', label: 'Königswinter' },
  { value: 'Köln', label: 'Köln' },
  { value: 'Kerpen', label: 'Kerpen' },
  { value: 'Kempen', label: 'Kempen' },
  { value: 'Herne-Wanne', label: 'Herne-Wanne' },
  { value: 'Heinsberg', label: 'Heinsberg' },
  { value: 'Hattingen', label: 'Hattingen' },
  { value: 'Halle (Westfalen)', label: 'Halle (Westfalen)' },
  { value: 'Gütersloh', label: 'Gütersloh' },
  { value: 'Gronau (Westfalen)', label: 'Gronau (Westfalen)' },
  { value: 'Düren', label: 'Düren' },
  { value: 'Duisburg', label: 'Duisburg' },
  { value: 'Dortmund', label: 'Dortmund' },
  { value: 'Bünde', label: 'Bünde' },
  { value: 'Bonn', label: 'Bonn' },
  { value: 'Bocholt', label: 'Bocholt' },
  { value: 'Bergisch Gladbach', label: 'Bergisch Gladbach' },
  { value: 'Bergheim', label: 'Bergheim' },
  { value: 'Beckum', label: 'Beckum' },
  { value: 'Bad Berleburg', label: 'Bad Berleburg' },
  { value: 'Aachen', label: 'Aachen' },
  { value: 'Bremen', label: 'Bremen' },
  { value: 'Zeven', label: 'Zeven' },
  { value: 'Winsen (Luhe)', label: 'Winsen (Luhe)' },
  { value: 'Wildeshausen', label: 'Wildeshausen' },
  { value: 'Tostedt', label: 'Tostedt' },
  { value: 'Syke', label: 'Syke' },
  { value: 'Sulingen', label: 'Sulingen' },
  { value: 'Stolzenau', label: 'Stolzenau' },
  { value: 'Seesen', label: 'Seesen' },
  { value: 'Rotenburg (Wümme)', label: 'Rotenburg (Wümme)' },
  { value: 'Peine', label: 'Peine' },
  { value: 'Papenburg', label: 'Papenburg' },
  { value: 'Osterode am Harz', label: 'Osterode am Harz' },
  { value: 'Osterholz-Scharmbeck', label: 'Osterholz-Scharmbeck' },
  { value: 'Osnabrück', label: 'Osnabrück' },
  { value: 'Oldenburg (Oldenburg)', label: 'Oldenburg (Oldenburg)' },
  { value: 'Neustadt am Rübenberge', label: 'Neustadt am Rübenberge' },
  { value: 'Lehrte', label: 'Lehrte' },
  { value: 'Hildesheim', label: 'Hildesheim' },
  { value: 'Helmstedt', label: 'Helmstedt' },
  { value: 'Hann. Münden', label: 'Hann. Münden' },
  { value: 'Hameln', label: 'Hameln' },
  { value: 'Gifhorn', label: 'Gifhorn' },
  { value: 'Elze', label: 'Elze' },
  { value: 'Einbeck', label: 'Einbeck' },
  { value: 'Cuxhaven', label: 'Cuxhaven' },
  { value: 'Buxtehude', label: 'Buxtehude' },
  { value: 'Burgdorf', label: 'Burgdorf' },
  { value: 'Bückeburg', label: 'Bückeburg' },
  { value: 'Bad Gandersheim', label: 'Bad Gandersheim' },
  { value: 'Alfeld (Leine)', label: 'Alfeld (Leine)' },
  { value: 'Achim', label: 'Achim' },
  { value: 'Hamburg-Harburg', label: 'Hamburg-Harburg' },
  { value: 'Ratzeburg', label: 'Ratzeburg' },
  { value: 'Oldenburg (Holstein)', label: 'Oldenburg (Holstein)' },
  { value: 'Norderstedt', label: 'Norderstedt' },
  { value: 'Itzehoe', label: 'Itzehoe' },
  { value: 'Husum', label: 'Husum' },
  { value: 'Eutin', label: 'Eutin' },
  { value: 'Eckernförde', label: 'Eckernförde' },
  { value: 'Bad Segeberg', label: 'Bad Segeberg' },
  {
    value: 'Obernburg am Main Zweigstelle Miltenberg',
    label: 'Obernburg am Main Zweigstelle Miltenberg',
  },
  { value: 'Obernburg am Main', label: 'Obernburg am Main' },
  { value: 'Nürnberg', label: 'Nürnberg' },
  { value: 'Neumarkt in der Oberpfalz', label: 'Neumarkt in der Oberpfalz' },
  { value: 'Neu-Ulm', label: 'Neu-Ulm' },
  { value: 'Mühldorf am Inn', label: 'Mühldorf am Inn' },
  { value: 'Laufen', label: 'Laufen' },
  { value: 'Landshut', label: 'Landshut' },
  { value: 'Landsberg am Lech', label: 'Landsberg am Lech' },
  { value: 'Landau a.d.Isar', label: 'Landau a.d.Isar' },
  { value: 'Kulmbach', label: 'Kulmbach' },
  { value: 'Ingolstadt', label: 'Ingolstadt' },
  { value: 'Fürstenfeldbruck', label: 'Fürstenfeldbruck' },
  { value: 'Freising', label: 'Freising' },
  { value: 'Dillingen an der Donau', label: 'Dillingen an der Donau' },
  { value: 'Cham', label: 'Cham' },
  { value: 'Bayreuth', label: 'Bayreuth' },
  { value: 'Bamberg', label: 'Bamberg' },
  { value: 'Augsburg', label: 'Augsburg' },
  { value: 'Wertheim', label: 'Wertheim' },
  { value: 'Wangen im Allgäu', label: 'Wangen im Allgäu' },
  { value: 'Ulm', label: 'Ulm' },
  { value: 'Tuttlingen', label: 'Tuttlingen' },
  { value: 'Schopfheim', label: 'Schopfheim' },
  { value: 'Rottenburg', label: 'Rottenburg' },
  { value: 'Riedlingen', label: 'Riedlingen' },
  { value: 'Reutlingen', label: 'Reutlingen' },
  { value: 'Ravensburg', label: 'Ravensburg' },
  { value: 'Radolfzell am Bodensee', label: 'Radolfzell am Bodensee' },
  { value: 'Oberndorf am Neckar', label: 'Oberndorf am Neckar' },
  { value: 'Nürtingen', label: 'Nürtingen' },
  { value: 'Neresheim', label: 'Neresheim' },
  { value: 'Nagold', label: 'Nagold' },
  { value: 'Maulbronn', label: 'Maulbronn' },
  { value: 'Mannheim', label: 'Mannheim' },
  { value: 'Ludwigsburg', label: 'Ludwigsburg' },
  { value: 'Lörrach', label: 'Lörrach' },
  { value: 'Leutkirch', label: 'Leutkirch' },
  { value: 'Langenburg', label: 'Langenburg' },
  { value: 'Konstanz', label: 'Konstanz' },
  { value: 'Heilbronn', label: 'Heilbronn' },
  { value: 'Heidelberg', label: 'Heidelberg' },
  { value: 'Göppingen', label: 'Göppingen' },
  { value: 'Gernsbach', label: 'Gernsbach' },
  { value: 'Gengenbach', label: 'Gengenbach' },
  { value: 'Ettenheim', label: 'Ettenheim' },
  { value: 'Ellwangen (Jagst)', label: 'Ellwangen (Jagst)' },
  { value: 'Donaueschingen', label: 'Donaueschingen' },
  { value: 'Buchen', label: 'Buchen' },
  { value: 'Bruchsal', label: 'Bruchsal' },
  { value: 'Bretten', label: 'Bretten' },
  { value: 'Brackenheim', label: 'Brackenheim' },
  { value: 'Baden-Baden', label: 'Baden-Baden' },
  { value: 'Bad Waldsee', label: 'Bad Waldsee' },
  { value: 'Bad Saulgau', label: 'Bad Saulgau' },
  { value: 'Albstadt', label: 'Albstadt' },
  { value: 'Achern', label: 'Achern' },
  { value: 'Zweibrücken', label: 'Zweibrücken' },
  { value: 'Westerburg', label: 'Westerburg' },
  { value: 'Speyer', label: 'Speyer' },
  { value: 'Pirmasens', label: 'Pirmasens' },
  { value: 'Neuwied', label: 'Neuwied' },
  { value: 'Neustadt an der Weinstraße', label: 'Neustadt an der Weinstraße' },
  { value: 'Montabaur', label: 'Montabaur' },
  { value: 'Ludwigshafen am Rhein', label: 'Ludwigshafen am Rhein' },
  { value: 'Landau in der Pfalz', label: 'Landau in der Pfalz' },
  { value: 'Lahnstein', label: 'Lahnstein' },
  { value: 'Kusel', label: 'Kusel' },
  { value: 'Idar-Oberstein', label: 'Idar-Oberstein' },
  { value: 'Grünstadt', label: 'Grünstadt' },
  { value: 'Frankenthal (Pfalz)', label: 'Frankenthal (Pfalz)' },
  { value: 'Bad Kreuznach', label: 'Bad Kreuznach' },
  { value: 'Wiesbaden', label: 'Wiesbaden' },
  { value: 'Wetzlar', label: 'Wetzlar' },
  { value: 'Rüsselsheim', label: 'Rüsselsheim' },
  { value: 'Rüdesheim am Rhein', label: 'Rüdesheim am Rhein' },
  { value: 'Offenbach am Main', label: 'Offenbach am Main' },
  { value: 'Lampertheim', label: 'Lampertheim' },
  { value: 'Kassel', label: 'Kassel' },
  { value: 'Idstein', label: 'Idstein' },
  { value: 'Fürth', label: 'Fürth' },
  { value: 'Fritzlar', label: 'Fritzlar' },
  { value: 'Frankfurt am Main', label: 'Frankfurt am Main' },
  { value: 'Eschwege', label: 'Eschwege' },
  { value: 'Darmstadt', label: 'Darmstadt' },
  { value: 'Biedenkopf', label: 'Biedenkopf' },
  { value: 'Bensheim', label: 'Bensheim' },
  { value: 'Alsfeld', label: 'Alsfeld' },
  { value: 'Witten', label: 'Witten' },
  { value: 'Wipperfürth', label: 'Wipperfürth' },
  { value: 'Werl', label: 'Werl' },
  { value: 'Warburg', label: 'Warburg' },
  { value: 'Viersen', label: 'Viersen' },
  { value: 'Velbert', label: 'Velbert' },
  { value: 'Tecklenburg', label: 'Tecklenburg' },
  { value: 'Steinfurt', label: 'Steinfurt' },
  { value: 'Soest', label: 'Soest' },
  { value: 'Siegen', label: 'Siegen' },
  { value: 'Siegburg', label: 'Siegburg' },
  { value: 'Rheinberg', label: 'Rheinberg' },
  { value: 'Recklinghausen', label: 'Recklinghausen' },
  { value: 'Rahden', label: 'Rahden' },
  { value: 'Plettenberg', label: 'Plettenberg' },
  { value: 'Oberhausen', label: 'Oberhausen' },
  { value: 'Nettetal', label: 'Nettetal' },
  { value: 'Münster', label: 'Münster' },
  { value: 'Medebach', label: 'Medebach' },
  { value: 'Marl', label: 'Marl' },
  { value: 'Lübbecke', label: 'Lübbecke' },
  { value: 'Leverkusen', label: 'Leverkusen' },
  { value: 'Lennestadt', label: 'Lennestadt' },
  { value: 'Kamen', label: 'Kamen' },
  { value: 'Jülich', label: 'Jülich' },
  { value: 'Iserlohn', label: 'Iserlohn' },
  { value: 'Höxter', label: 'Höxter' },
  { value: 'Herne', label: 'Herne' },
  { value: 'Grevenbroich', label: 'Grevenbroich' },
  { value: 'Gladbeck', label: 'Gladbeck' },
  { value: 'Gelsenkirchen', label: 'Gelsenkirchen' },
  { value: 'Geldern', label: 'Geldern' },
  { value: 'Geilenkirchen', label: 'Geilenkirchen' },
  { value: 'Essen-Steele', label: 'Essen-Steele' },
  { value: 'Emmerich am Rhein', label: 'Emmerich am Rhein' },
  { value: 'Düsseldorf', label: 'Düsseldorf' },
  { value: 'Dülmen', label: 'Dülmen' },
  { value: 'Duisburg-Hamborn', label: 'Duisburg-Hamborn' },
  { value: 'Dorsten', label: 'Dorsten' },
  { value: 'Detmold', label: 'Detmold' },
  { value: 'Brühl', label: 'Brühl' },
  { value: 'Borken', label: 'Borken' },
  { value: 'Blomberg', label: 'Blomberg' },
  { value: 'Arnsberg', label: 'Arnsberg' },
  { value: 'Altena', label: 'Altena' },
  { value: 'Ahlen', label: 'Ahlen' },
  { value: 'Bremen-Blumenthal', label: 'Bremen-Blumenthal' },
  { value: 'Wolfenbüttel', label: 'Wolfenbüttel' },
  { value: 'Wittmund', label: 'Wittmund' },
  { value: 'Wilhelmshaven', label: 'Wilhelmshaven' },
  { value: 'Westerstede', label: 'Westerstede' },
  { value: 'Wennigsen (Deister)', label: 'Wennigsen (Deister)' },
  { value: 'Vechta', label: 'Vechta' },
  { value: 'Uelzen', label: 'Uelzen' },
  { value: 'Springe', label: 'Springe' },
  { value: 'Salzgitter', label: 'Salzgitter' },
  { value: 'Otterndorf', label: 'Otterndorf' },
  { value: 'Nordhorn', label: 'Nordhorn' },
  { value: 'Nienburg (Weser)', label: 'Nienburg (Weser)' },
  { value: 'Lingen (Ems)', label: 'Lingen (Ems)' },
  { value: 'Göttingen', label: 'Göttingen' },
  { value: 'Goslar', label: 'Goslar' },
  { value: 'Geestland', label: 'Geestland' },
  { value: 'Emden', label: 'Emden' },
  { value: 'Duderstadt', label: 'Duderstadt' },
  { value: 'Delmenhorst', label: 'Delmenhorst' },
  { value: 'Dannenberg', label: 'Dannenberg' },
  { value: 'Clausthal-Zellerfeld', label: 'Clausthal-Zellerfeld' },
  { value: 'Bremervörde', label: 'Bremervörde' },
  { value: 'Braunschweig', label: 'Braunschweig' },
  { value: 'Bad Iburg', label: 'Bad Iburg' },
  { value: 'Aurich', label: 'Aurich' },
  { value: 'Hamburg-Wandsbek', label: 'Hamburg-Wandsbek' },
  { value: 'Hamburg-Blankenese', label: 'Hamburg-Blankenese' },
  { value: 'Hamburg-Bergedorf', label: 'Hamburg-Bergedorf' },
  { value: 'Hamburg-Barmbek', label: 'Hamburg-Barmbek' },
  { value: 'Hamburg-Altona', label: 'Hamburg-Altona' },
  { value: 'Schwarzenbek', label: 'Schwarzenbek' },
  { value: 'Schleswig', label: 'Schleswig' },
  { value: 'Neumünster', label: 'Neumünster' },
  { value: 'Meldorf', label: 'Meldorf' },
  { value: 'Lübeck', label: 'Lübeck' },
  { value: 'Flensburg', label: 'Flensburg' },
  { value: 'Suhl', label: 'Suhl' },
  { value: 'Pößneck Zweigstelle Bad Lobenstein', label: 'Pößneck Zweigstelle Bad Lobenstein' },
  { value: 'Hildburghausen', label: 'Hildburghausen' },
  { value: 'Gotha', label: 'Gotha' },
  { value: 'Eisenach', label: 'Eisenach' },
  { value: 'Apolda', label: 'Apolda' },
  { value: 'Wittenberg', label: 'Wittenberg' },
  { value: 'Wernigerode', label: 'Wernigerode' },
  { value: 'Stendal', label: 'Stendal' },
  { value: 'Schönebeck', label: 'Schönebeck' },
  { value: 'Naumburg', label: 'Naumburg' },
  { value: 'Halberstadt', label: 'Halberstadt' },
  { value: 'Eisleben', label: 'Eisleben' },
  { value: 'Burg', label: 'Burg' },
  { value: 'Weißwasser', label: 'Weißwasser' },
  { value: 'Torgau', label: 'Torgau' },
  { value: 'Riesa', label: 'Riesa' },
  { value: 'Marienberg', label: 'Marienberg' },
  { value: 'Kamenz', label: 'Kamenz' },
  { value: 'Görlitz', label: 'Görlitz' },
  { value: 'Döbeln Zweigstelle Hainichen', label: 'Döbeln Zweigstelle Hainichen' },
  { value: 'Döbeln', label: 'Döbeln' },
  { value: 'Dippoldiswalde', label: 'Dippoldiswalde' },
  { value: 'Bautzen', label: 'Bautzen' },
  { value: 'Auerbach', label: 'Auerbach' },
  {
    value: 'Stralsund Zweigstelle Bergen auf Rügen',
    label: 'Stralsund Zweigstelle Bergen auf Rügen',
  },
  { value: 'Stralsund', label: 'Stralsund' },
  { value: 'Schwerin', label: 'Schwerin' },
  { value: 'Ludwigslust Zweigstelle Parchim', label: 'Ludwigslust Zweigstelle Parchim' },
  { value: 'Güstrow', label: 'Güstrow' },
  { value: 'Strausberg', label: 'Strausberg' },
  { value: 'Schwedt/Oder', label: 'Schwedt/Oder' },
  { value: 'Rathenow', label: 'Rathenow' },
  { value: 'Oranienburg', label: 'Oranienburg' },
  { value: 'Nauen', label: 'Nauen' },
  { value: 'Eberswalde', label: 'Eberswalde' },
  { value: 'Cottbus Zweigstelle Guben', label: 'Cottbus Zweigstelle Guben' },
  { value: 'Brandenburg an der Havel', label: 'Brandenburg an der Havel' },
  { value: 'Wedding', label: 'Wedding' },
  { value: 'Tiergarten', label: 'Tiergarten' },
  { value: 'Schöneberg', label: 'Schöneberg' },
  { value: 'Charlottenburg', label: 'Charlottenburg' },
  { value: 'Neunkirchen', label: 'Neunkirchen' },
  { value: 'Merzig Zweigstelle Wadern', label: 'Merzig Zweigstelle Wadern' },
  { value: 'Wunsiedel', label: 'Wunsiedel' },
  { value: 'Traunstein', label: 'Traunstein' },
  { value: 'Starnberg', label: 'Starnberg' },
  { value: 'Schwandorf', label: 'Schwandorf' },
];
