// @todo - Remove with API call.
type CountryData = {
  id: number;
  name: string;
  iso2: string;
  translations: { de?: string };
  emoji: string;
};

export const COUNTRIES_DATA: CountryData[] = [
  { id: 1, name: 'Afghanistan', iso2: 'AF', translations: { de: 'Afghanistan' }, emoji: '🇦🇫' },
  { id: 2, name: 'Aland Islands', iso2: 'AX', translations: { de: 'Åland' }, emoji: '🇦🇽' },
  { id: 3, name: 'Albania', iso2: 'AL', translations: { de: 'Albanien' }, emoji: '🇦🇱' },
  { id: 4, name: 'Algeria', iso2: 'DZ', translations: { de: 'Algerien' }, emoji: '🇩🇿' },
  {
    id: 5,
    name: 'American Samoa',
    iso2: 'AS',
    translations: { de: 'Amerikanisch-Samoa' },
    emoji: '🇦🇸',
  },
  { id: 6, name: 'Andorra', iso2: 'AD', translations: { de: 'Andorra' }, emoji: '🇦🇩' },
  { id: 7, name: 'Angola', iso2: 'AO', translations: { de: 'Angola' }, emoji: '🇦🇴' },
  { id: 8, name: 'Anguilla', iso2: 'AI', translations: { de: 'Anguilla' }, emoji: '🇦🇮' },
  { id: 9, name: 'Antarctica', iso2: 'AQ', translations: { de: 'Antarktika' }, emoji: '🇦🇶' },
  {
    id: 10,
    name: 'Antigua and Barbuda',
    iso2: 'AG',
    translations: { de: 'Antigua und Barbuda' },
    emoji: '🇦🇬',
  },
  { id: 11, name: 'Argentina', iso2: 'AR', translations: { de: 'Argentinien' }, emoji: '🇦🇷' },
  { id: 12, name: 'Armenia', iso2: 'AM', translations: { de: 'Armenien' }, emoji: '🇦🇲' },
  { id: 13, name: 'Aruba', iso2: 'AW', translations: { de: 'Aruba' }, emoji: '🇦🇼' },
  { id: 14, name: 'Australia', iso2: 'AU', translations: { de: 'Australien' }, emoji: '🇦🇺' },
  { id: 15, name: 'Austria', iso2: 'AT', translations: { de: 'Österreich' }, emoji: '🇦🇹' },
  { id: 16, name: 'Azerbaijan', iso2: 'AZ', translations: { de: 'Aserbaidschan' }, emoji: '🇦🇿' },
  { id: 18, name: 'Bahrain', iso2: 'BH', translations: { de: 'Bahrain' }, emoji: '🇧🇭' },
  { id: 19, name: 'Bangladesh', iso2: 'BD', translations: { de: 'Bangladesch' }, emoji: '🇧🇩' },
  { id: 20, name: 'Barbados', iso2: 'BB', translations: { de: 'Barbados' }, emoji: '🇧🇧' },
  { id: 21, name: 'Belarus', iso2: 'BY', translations: { de: 'Weißrussland' }, emoji: '🇧🇾' },
  { id: 22, name: 'Belgium', iso2: 'BE', translations: { de: 'Belgien' }, emoji: '🇧🇪' },
  { id: 23, name: 'Belize', iso2: 'BZ', translations: { de: 'Belize' }, emoji: '🇧🇿' },
  { id: 24, name: 'Benin', iso2: 'BJ', translations: { de: 'Benin' }, emoji: '🇧🇯' },
  { id: 25, name: 'Bermuda', iso2: 'BM', translations: { de: 'Bermuda' }, emoji: '🇧🇲' },
  { id: 26, name: 'Bhutan', iso2: 'BT', translations: { de: 'Bhutan' }, emoji: '🇧🇹' },
  { id: 27, name: 'Bolivia', iso2: 'BO', translations: { de: 'Bolivien' }, emoji: '🇧🇴' },
  {
    id: 155,
    name: 'Bonaire, Sint Eustatius and Saba',
    iso2: 'BQ',
    translations: { de: 'Bonaire, Sint Eustatius und Saba' },
    emoji: '🇧🇶',
  },
  {
    id: 28,
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    translations: { de: 'Bosnien und Herzegowina' },
    emoji: '🇧🇦',
  },
  { id: 29, name: 'Botswana', iso2: 'BW', translations: { de: 'Botswana' }, emoji: '🇧🇼' },
  { id: 30, name: 'Bouvet Island', iso2: 'BV', translations: { de: 'Bouvetinsel' }, emoji: '🇧🇻' },
  { id: 31, name: 'Brazil', iso2: 'BR', translations: { de: 'Brasilien' }, emoji: '🇧🇷' },
  {
    id: 32,
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    translations: { de: 'Britisches Territorium im Indischen Ozean' },
    emoji: '🇮🇴',
  },
  { id: 33, name: 'Brunei', iso2: 'BN', translations: { de: 'Brunei' }, emoji: '🇧🇳' },
  { id: 34, name: 'Bulgaria', iso2: 'BG', translations: { de: 'Bulgarien' }, emoji: '🇧🇬' },
  { id: 35, name: 'Burkina Faso', iso2: 'BF', translations: { de: 'Burkina Faso' }, emoji: '🇧🇫' },
  { id: 36, name: 'Burundi', iso2: 'BI', translations: { de: 'Burundi' }, emoji: '🇧🇮' },
  { id: 37, name: 'Cambodia', iso2: 'KH', translations: { de: 'Kambodscha' }, emoji: '🇰🇭' },
  { id: 38, name: 'Cameroon', iso2: 'CM', translations: { de: 'Kamerun' }, emoji: '🇨🇲' },
  { id: 39, name: 'Canada', iso2: 'CA', translations: { de: 'Kanada' }, emoji: '🇨🇦' },
  { id: 40, name: 'Cape Verde', iso2: 'CV', translations: { de: 'Kap Verde' }, emoji: '🇨🇻' },
  { id: 41, name: 'Cayman Islands', iso2: 'KY', translations: { de: 'Kaimaninseln' }, emoji: '🇰🇾' },
  {
    id: 42,
    name: 'Central African Republic',
    iso2: 'CF',
    translations: { de: 'Zentralafrikanische Republik' },
    emoji: '🇨🇫',
  },
  { id: 43, name: 'Chad', iso2: 'TD', translations: { de: 'Tschad' }, emoji: '🇹🇩' },
  { id: 44, name: 'Chile', iso2: 'CL', translations: { de: 'Chile' }, emoji: '🇨🇱' },
  { id: 45, name: 'China', iso2: 'CN', translations: { de: 'China' }, emoji: '🇨🇳' },
  {
    id: 46,
    name: 'Christmas Island',
    iso2: 'CX',
    translations: { de: 'Weihnachtsinsel' },
    emoji: '🇨🇽',
  },
  {
    id: 47,
    name: 'Cocos (Keeling) Islands',
    iso2: 'CC',
    translations: { de: 'Kokosinseln' },
    emoji: '🇨🇨',
  },
  { id: 48, name: 'Colombia', iso2: 'CO', translations: { de: 'Kolumbien' }, emoji: '🇨🇴' },
  { id: 49, name: 'Comoros', iso2: 'KM', translations: { de: 'Union der Komoren' }, emoji: '🇰🇲' },
  { id: 50, name: 'Congo', iso2: 'CG', translations: { de: 'Kongo' }, emoji: '🇨🇬' },
  { id: 52, name: 'Cook Islands', iso2: 'CK', translations: { de: 'Cookinseln' }, emoji: '🇨🇰' },
  { id: 53, name: 'Costa Rica', iso2: 'CR', translations: { de: 'Costa Rica' }, emoji: '🇨🇷' },
  {
    id: 54,
    name: "Cote D'Ivoire (Ivory Coast)",
    iso2: 'CI',
    translations: { de: 'Elfenbeinküste' },
    emoji: '🇨🇮',
  },
  { id: 55, name: 'Croatia', iso2: 'HR', translations: { de: 'Kroatien' }, emoji: '🇭🇷' },
  { id: 56, name: 'Cuba', iso2: 'CU', translations: { de: 'Kuba' }, emoji: '🇨🇺' },
  { id: 249, name: 'Curaçao', iso2: 'CW', translations: { de: 'Curaçao' }, emoji: '🇨🇼' },
  { id: 57, name: 'Cyprus', iso2: 'CY', translations: { de: 'Zypern' }, emoji: '🇨🇾' },
  {
    id: 58,
    name: 'Czech Republic',
    iso2: 'CZ',
    translations: { de: 'Tschechische Republik' },
    emoji: '🇨🇿',
  },
  {
    id: 51,
    name: 'Democratic Republic of the Congo',
    iso2: 'CD',
    translations: { de: 'Kongo (Dem. Rep.)' },
    emoji: '🇨🇩',
  },
  { id: 59, name: 'Denmark', iso2: 'DK', translations: { de: 'Dänemark' }, emoji: '🇩🇰' },
  { id: 60, name: 'Djibouti', iso2: 'DJ', translations: { de: 'Dschibuti' }, emoji: '🇩🇯' },
  { id: 61, name: 'Dominica', iso2: 'DM', translations: { de: 'Dominica' }, emoji: '🇩🇲' },
  {
    id: 62,
    name: 'Dominican Republic',
    iso2: 'DO',
    translations: { de: 'Dominikanische Republik' },
    emoji: '🇩🇴',
  },
  { id: 64, name: 'Ecuador', iso2: 'EC', translations: { de: 'Ecuador' }, emoji: '🇪🇨' },
  { id: 65, name: 'Egypt', iso2: 'EG', translations: { de: 'Ägypten' }, emoji: '🇪🇬' },
  { id: 66, name: 'El Salvador', iso2: 'SV', translations: { de: 'El Salvador' }, emoji: '🇸🇻' },
  {
    id: 67,
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    translations: { de: 'Äquatorial-Guinea' },
    emoji: '🇬🇶',
  },
  { id: 68, name: 'Eritrea', iso2: 'ER', translations: { de: 'Eritrea' }, emoji: '🇪🇷' },
  { id: 69, name: 'Estonia', iso2: 'EE', translations: { de: 'Estland' }, emoji: '🇪🇪' },
  { id: 212, name: 'Eswatini', iso2: 'SZ', translations: { de: 'Swasiland' }, emoji: '🇸🇿' },
  { id: 70, name: 'Ethiopia', iso2: 'ET', translations: { de: 'Äthiopien' }, emoji: '🇪🇹' },
  {
    id: 71,
    name: 'Falkland Islands',
    iso2: 'FK',
    translations: { de: 'Falklandinseln' },
    emoji: '🇫🇰',
  },
  { id: 72, name: 'Faroe Islands', iso2: 'FO', translations: { de: 'Färöer-Inseln' }, emoji: '🇫🇴' },
  { id: 73, name: 'Fiji Islands', iso2: 'FJ', translations: { de: 'Fidschi' }, emoji: '🇫🇯' },
  { id: 74, name: 'Finland', iso2: 'FI', translations: { de: 'Finnland' }, emoji: '🇫🇮' },
  { id: 75, name: 'France', iso2: 'FR', translations: { de: 'Frankreich' }, emoji: '🇫🇷' },
  {
    id: 76,
    name: 'French Guiana',
    iso2: 'GF',
    translations: { de: 'Französisch Guyana' },
    emoji: '🇬🇫',
  },
  {
    id: 77,
    name: 'French Polynesia',
    iso2: 'PF',
    translations: { de: 'Französisch-Polynesien' },
    emoji: '🇵🇫',
  },
  {
    id: 78,
    name: 'French Southern Territories',
    iso2: 'TF',
    translations: { de: 'Französische Süd- und Antarktisgebiete' },
    emoji: '🇹🇫',
  },
  { id: 79, name: 'Gabon', iso2: 'GA', translations: { de: 'Gabun' }, emoji: '🇬🇦' },
  { id: 80, name: 'Gambia The', iso2: 'GM', translations: { de: 'Gambia' }, emoji: '🇬🇲' },
  { id: 81, name: 'Georgia', iso2: 'GE', translations: { de: 'Georgien' }, emoji: '🇬🇪' },
  { id: 82, name: 'Germany', iso2: 'DE', translations: { de: 'Deutschland' }, emoji: '🇩🇪' },
  { id: 83, name: 'Ghana', iso2: 'GH', translations: { de: 'Ghana' }, emoji: '🇬🇭' },
  { id: 84, name: 'Gibraltar', iso2: 'GI', translations: { de: 'Gibraltar' }, emoji: '🇬🇮' },
  { id: 85, name: 'Greece', iso2: 'GR', translations: { de: 'Griechenland' }, emoji: '🇬🇷' },
  { id: 86, name: 'Greenland', iso2: 'GL', translations: { de: 'Grönland' }, emoji: '🇬🇱' },
  { id: 87, name: 'Grenada', iso2: 'GD', translations: { de: 'Grenada' }, emoji: '🇬🇩' },
  { id: 88, name: 'Guadeloupe', iso2: 'GP', translations: { de: 'Guadeloupe' }, emoji: '🇬🇵' },
  { id: 89, name: 'Guam', iso2: 'GU', translations: { de: 'Guam' }, emoji: '🇬🇺' },
  { id: 90, name: 'Guatemala', iso2: 'GT', translations: { de: 'Guatemala' }, emoji: '🇬🇹' },
  {
    id: 91,
    name: 'Guernsey and Alderney',
    iso2: 'GG',
    translations: { de: 'Guernsey' },
    emoji: '🇬🇬',
  },
  { id: 92, name: 'Guinea', iso2: 'GN', translations: { de: 'Guinea' }, emoji: '🇬🇳' },
  { id: 93, name: 'Guinea-Bissau', iso2: 'GW', translations: { de: 'Guinea-Bissau' }, emoji: '🇬🇼' },
  { id: 94, name: 'Guyana', iso2: 'GY', translations: { de: 'Guyana' }, emoji: '🇬🇾' },
  { id: 95, name: 'Haiti', iso2: 'HT', translations: { de: 'Haiti' }, emoji: '🇭🇹' },
  {
    id: 96,
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    translations: { de: 'Heard und die McDonaldinseln' },
    emoji: '🇭🇲',
  },
  { id: 97, name: 'Honduras', iso2: 'HN', translations: { de: 'Honduras' }, emoji: '🇭🇳' },
  { id: 98, name: 'Hong Kong S.A.R.', iso2: 'HK', translations: { de: 'Hong Kong' }, emoji: '🇭🇰' },
  { id: 99, name: 'Hungary', iso2: 'HU', translations: { de: 'Ungarn' }, emoji: '🇭🇺' },
  { id: 100, name: 'Iceland', iso2: 'IS', translations: { de: 'Island' }, emoji: '🇮🇸' },
  { id: 101, name: 'India', iso2: 'IN', translations: { de: 'Indien' }, emoji: '🇮🇳' },
  { id: 102, name: 'Indonesia', iso2: 'ID', translations: { de: 'Indonesien' }, emoji: '🇮🇩' },
  { id: 103, name: 'Iran', iso2: 'IR', translations: { de: 'Iran' }, emoji: '🇮🇷' },
  { id: 104, name: 'Iraq', iso2: 'IQ', translations: { de: 'Irak' }, emoji: '🇮🇶' },
  { id: 105, name: 'Ireland', iso2: 'IE', translations: { de: 'Irland' }, emoji: '🇮🇪' },
  { id: 106, name: 'Israel', iso2: 'IL', translations: { de: 'Israel' }, emoji: '🇮🇱' },
  { id: 107, name: 'Italy', iso2: 'IT', translations: { de: 'Italien' }, emoji: '🇮🇹' },
  { id: 108, name: 'Jamaica', iso2: 'JM', translations: { de: 'Jamaika' }, emoji: '🇯🇲' },
  { id: 109, name: 'Japan', iso2: 'JP', translations: { de: 'Japan' }, emoji: '🇯🇵' },
  { id: 110, name: 'Jersey', iso2: 'JE', translations: { de: 'Jersey' }, emoji: '🇯🇪' },
  { id: 111, name: 'Jordan', iso2: 'JO', translations: { de: 'Jordanien' }, emoji: '🇯🇴' },
  { id: 112, name: 'Kazakhstan', iso2: 'KZ', translations: { de: 'Kasachstan' }, emoji: '🇰🇿' },
  { id: 113, name: 'Kenya', iso2: 'KE', translations: { de: 'Kenia' }, emoji: '🇰🇪' },
  { id: 114, name: 'Kiribati', iso2: 'KI', translations: { de: 'Kiribati' }, emoji: '🇰🇮' },
  { id: 248, name: 'Kosovo', iso2: 'XK', translations: {}, emoji: '🇽🇰' },
  { id: 117, name: 'Kuwait', iso2: 'KW', translations: { de: 'Kuwait' }, emoji: '🇰🇼' },
  { id: 118, name: 'Kyrgyzstan', iso2: 'KG', translations: { de: 'Kirgisistan' }, emoji: '🇰🇬' },
  { id: 119, name: 'Laos', iso2: 'LA', translations: { de: 'Laos' }, emoji: '🇱🇦' },
  { id: 120, name: 'Latvia', iso2: 'LV', translations: { de: 'Lettland' }, emoji: '🇱🇻' },
  { id: 121, name: 'Lebanon', iso2: 'LB', translations: { de: 'Libanon' }, emoji: '🇱🇧' },
  { id: 122, name: 'Lesotho', iso2: 'LS', translations: { de: 'Lesotho' }, emoji: '🇱🇸' },
  { id: 123, name: 'Liberia', iso2: 'LR', translations: { de: 'Liberia' }, emoji: '🇱🇷' },
  { id: 124, name: 'Libya', iso2: 'LY', translations: { de: 'Libyen' }, emoji: '🇱🇾' },
  {
    id: 125,
    name: 'Liechtenstein',
    iso2: 'LI',
    translations: { de: 'Liechtenstein' },
    emoji: '🇱🇮',
  },
  { id: 126, name: 'Lithuania', iso2: 'LT', translations: { de: 'Litauen' }, emoji: '🇱🇹' },
  { id: 127, name: 'Luxembourg', iso2: 'LU', translations: { de: 'Luxemburg' }, emoji: '🇱🇺' },
  { id: 128, name: 'Macau S.A.R.', iso2: 'MO', translations: { de: 'Macao' }, emoji: '🇲🇴' },
  { id: 130, name: 'Madagascar', iso2: 'MG', translations: { de: 'Madagaskar' }, emoji: '🇲🇬' },
  { id: 131, name: 'Malawi', iso2: 'MW', translations: { de: 'Malawi' }, emoji: '🇲🇼' },
  { id: 132, name: 'Malaysia', iso2: 'MY', translations: { de: 'Malaysia' }, emoji: '🇲🇾' },
  { id: 133, name: 'Maldives', iso2: 'MV', translations: { de: 'Malediven' }, emoji: '🇲🇻' },
  { id: 134, name: 'Mali', iso2: 'ML', translations: { de: 'Mali' }, emoji: '🇲🇱' },
  { id: 135, name: 'Malta', iso2: 'MT', translations: { de: 'Malta' }, emoji: '🇲🇹' },
  { id: 136, name: 'Man (Isle of)', iso2: 'IM', translations: { de: 'Insel Man' }, emoji: '🇮🇲' },
  {
    id: 137,
    name: 'Marshall Islands',
    iso2: 'MH',
    translations: { de: 'Marshallinseln' },
    emoji: '🇲🇭',
  },
  { id: 138, name: 'Martinique', iso2: 'MQ', translations: { de: 'Martinique' }, emoji: '🇲🇶' },
  { id: 139, name: 'Mauritania', iso2: 'MR', translations: { de: 'Mauretanien' }, emoji: '🇲🇷' },
  { id: 140, name: 'Mauritius', iso2: 'MU', translations: { de: 'Mauritius' }, emoji: '🇲🇺' },
  { id: 141, name: 'Mayotte', iso2: 'YT', translations: { de: 'Mayotte' }, emoji: '🇾🇹' },
  { id: 142, name: 'Mexico', iso2: 'MX', translations: { de: 'Mexiko' }, emoji: '🇲🇽' },
  { id: 143, name: 'Micronesia', iso2: 'FM', translations: { de: 'Mikronesien' }, emoji: '🇫🇲' },
  { id: 144, name: 'Moldova', iso2: 'MD', translations: { de: 'Moldawie' }, emoji: '🇲🇩' },
  { id: 145, name: 'Monaco', iso2: 'MC', translations: { de: 'Monaco' }, emoji: '🇲🇨' },
  { id: 146, name: 'Mongolia', iso2: 'MN', translations: { de: 'Mongolei' }, emoji: '🇲🇳' },
  { id: 147, name: 'Montenegro', iso2: 'ME', translations: { de: 'Montenegro' }, emoji: '🇲🇪' },
  { id: 148, name: 'Montserrat', iso2: 'MS', translations: { de: 'Montserrat' }, emoji: '🇲🇸' },
  { id: 149, name: 'Morocco', iso2: 'MA', translations: { de: 'Marokko' }, emoji: '🇲🇦' },
  { id: 150, name: 'Mozambique', iso2: 'MZ', translations: { de: 'Mosambik' }, emoji: '🇲🇿' },
  { id: 151, name: 'Myanmar', iso2: 'MM', translations: { de: 'Myanmar' }, emoji: '🇲🇲' },
  { id: 152, name: 'Namibia', iso2: 'NA', translations: { de: 'Namibia' }, emoji: '🇳🇦' },
  { id: 153, name: 'Nauru', iso2: 'NR', translations: { de: 'Nauru' }, emoji: '🇳🇷' },
  { id: 154, name: 'Nepal', iso2: 'NP', translations: { de: 'Népal' }, emoji: '🇳🇵' },
  { id: 156, name: 'Netherlands', iso2: 'NL', translations: { de: 'Niederlande' }, emoji: '🇳🇱' },
  {
    id: 157,
    name: 'New Caledonia',
    iso2: 'NC',
    translations: { de: 'Neukaledonien' },
    emoji: '🇳🇨',
  },
  { id: 158, name: 'New Zealand', iso2: 'NZ', translations: { de: 'Neuseeland' }, emoji: '🇳🇿' },
  { id: 159, name: 'Nicaragua', iso2: 'NI', translations: { de: 'Nicaragua' }, emoji: '🇳🇮' },
  { id: 160, name: 'Niger', iso2: 'NE', translations: { de: 'Niger' }, emoji: '🇳🇪' },
  { id: 161, name: 'Nigeria', iso2: 'NG', translations: { de: 'Nigeria' }, emoji: '🇳🇬' },
  { id: 162, name: 'Niue', iso2: 'NU', translations: { de: 'Niue' }, emoji: '🇳🇺' },
  {
    id: 163,
    name: 'Norfolk Island',
    iso2: 'NF',
    translations: { de: 'Norfolkinsel' },
    emoji: '🇳🇫',
  },
  { id: 115, name: 'North Korea', iso2: 'KP', translations: { de: 'Nordkorea' }, emoji: '🇰🇵' },
  {
    id: 129,
    name: 'North Macedonia',
    iso2: 'MK',
    translations: { de: 'Nordmazedonien' },
    emoji: '🇲🇰',
  },
  {
    id: 164,
    name: 'Northern Mariana Islands',
    iso2: 'MP',
    translations: { de: 'Nördliche Marianen' },
    emoji: '🇲🇵',
  },
  { id: 165, name: 'Norway', iso2: 'NO', translations: { de: 'Norwegen' }, emoji: '🇳🇴' },
  { id: 166, name: 'Oman', iso2: 'OM', translations: { de: 'Oman' }, emoji: '🇴🇲' },
  { id: 167, name: 'Pakistan', iso2: 'PK', translations: { de: 'Pakistan' }, emoji: '🇵🇰' },
  { id: 168, name: 'Palau', iso2: 'PW', translations: { de: 'Palau' }, emoji: '🇵🇼' },
  {
    id: 169,
    name: 'Palestinian Territory Occupied',
    iso2: 'PS',
    translations: { de: 'Palästina' },
    emoji: '🇵🇸',
  },
  { id: 170, name: 'Panama', iso2: 'PA', translations: { de: 'Panama' }, emoji: '🇵🇦' },
  {
    id: 171,
    name: 'Papua New Guinea',
    iso2: 'PG',
    translations: { de: 'Papua-Neuguinea' },
    emoji: '🇵🇬',
  },
  { id: 172, name: 'Paraguay', iso2: 'PY', translations: { de: 'Paraguay' }, emoji: '🇵🇾' },
  { id: 173, name: 'Peru', iso2: 'PE', translations: { de: 'Peru' }, emoji: '🇵🇪' },
  { id: 174, name: 'Philippines', iso2: 'PH', translations: { de: 'Philippinen' }, emoji: '🇵🇭' },
  { id: 175, name: 'Pitcairn Island', iso2: 'PN', translations: { de: 'Pitcairn' }, emoji: '🇵🇳' },
  { id: 176, name: 'Poland', iso2: 'PL', translations: { de: 'Polen' }, emoji: '🇵🇱' },
  { id: 177, name: 'Portugal', iso2: 'PT', translations: { de: 'Portugal' }, emoji: '🇵🇹' },
  { id: 178, name: 'Puerto Rico', iso2: 'PR', translations: { de: 'Puerto Rico' }, emoji: '🇵🇷' },
  { id: 179, name: 'Qatar', iso2: 'QA', translations: { de: 'Katar' }, emoji: '🇶🇦' },
  { id: 180, name: 'Reunion', iso2: 'RE', translations: { de: 'Réunion' }, emoji: '🇷🇪' },
  { id: 181, name: 'Romania', iso2: 'RO', translations: { de: 'Rumänien' }, emoji: '🇷🇴' },
  { id: 182, name: 'Russia', iso2: 'RU', translations: { de: 'Russland' }, emoji: '🇷🇺' },
  { id: 183, name: 'Rwanda', iso2: 'RW', translations: { de: 'Ruanda' }, emoji: '🇷🇼' },
  { id: 184, name: 'Saint Helena', iso2: 'SH', translations: { de: 'Sankt Helena' }, emoji: '🇸🇭' },
  {
    id: 185,
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    translations: { de: 'St. Kitts und Nevis' },
    emoji: '🇰🇳',
  },
  { id: 186, name: 'Saint Lucia', iso2: 'LC', translations: { de: 'Saint Lucia' }, emoji: '🇱🇨' },
  {
    id: 187,
    name: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    translations: { de: 'Saint-Pierre und Miquelon' },
    emoji: '🇵🇲',
  },
  {
    id: 188,
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    translations: { de: 'Saint Vincent und die Grenadinen' },
    emoji: '🇻🇨',
  },
  {
    id: 189,
    name: 'Saint-Barthelemy',
    iso2: 'BL',
    translations: { de: 'Saint-Barthélemy' },
    emoji: '🇧🇱',
  },
  {
    id: 190,
    name: 'Saint-Martin (French part)',
    iso2: 'MF',
    translations: { de: 'Saint Martin' },
    emoji: '🇲🇫',
  },
  { id: 191, name: 'Samoa', iso2: 'WS', translations: { de: 'Samoa' }, emoji: '🇼🇸' },
  { id: 192, name: 'San Marino', iso2: 'SM', translations: { de: 'San Marino' }, emoji: '🇸🇲' },
  {
    id: 193,
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    translations: { de: 'São Tomé und Príncipe' },
    emoji: '🇸🇹',
  },
  { id: 194, name: 'Saudi Arabia', iso2: 'SA', translations: { de: 'Saudi-Arabien' }, emoji: '🇸🇦' },
  { id: 195, name: 'Senegal', iso2: 'SN', translations: { de: 'Senegal' }, emoji: '🇸🇳' },
  { id: 196, name: 'Serbia', iso2: 'RS', translations: { de: 'Serbien' }, emoji: '🇷🇸' },
  { id: 197, name: 'Seychelles', iso2: 'SC', translations: { de: 'Seychellen' }, emoji: '🇸🇨' },
  { id: 198, name: 'Sierra Leone', iso2: 'SL', translations: { de: 'Sierra Leone' }, emoji: '🇸🇱' },
  { id: 199, name: 'Singapore', iso2: 'SG', translations: { de: 'Singapur' }, emoji: '🇸🇬' },
  {
    id: 250,
    name: 'Sint Maarten (Dutch part)',
    iso2: 'SX',
    translations: { de: 'Sint Maarten (niederl. Teil)' },
    emoji: '🇸🇽',
  },
  { id: 200, name: 'Slovakia', iso2: 'SK', translations: { de: 'Slowakei' }, emoji: '🇸🇰' },
  { id: 201, name: 'Slovenia', iso2: 'SI', translations: { de: 'Slowenien' }, emoji: '🇸🇮' },
  { id: 202, name: 'Solomon Islands', iso2: 'SB', translations: { de: 'Salomonen' }, emoji: '🇸🇧' },
  { id: 203, name: 'Somalia', iso2: 'SO', translations: { de: 'Somalia' }, emoji: '🇸🇴' },
  {
    id: 204,
    name: 'South Africa',
    iso2: 'ZA',
    translations: { de: 'Republik Südafrika' },
    emoji: '🇿🇦',
  },
  {
    id: 205,
    name: 'South Georgia',
    iso2: 'GS',
    translations: { de: 'Südgeorgien und die Südlichen Sandwichinseln' },
    emoji: '🇬🇸',
  },
  { id: 116, name: 'South Korea', iso2: 'KR', translations: { de: 'Südkorea' }, emoji: '🇰🇷' },
  { id: 206, name: 'South Sudan', iso2: 'SS', translations: { de: 'Südsudan' }, emoji: '🇸🇸' },
  { id: 207, name: 'Spain', iso2: 'ES', translations: { de: 'Spanien' }, emoji: '🇪🇸' },
  { id: 208, name: 'Sri Lanka', iso2: 'LK', translations: { de: 'Sri Lanka' }, emoji: '🇱🇰' },
  { id: 209, name: 'Sudan', iso2: 'SD', translations: { de: 'Sudan' }, emoji: '🇸🇩' },
  { id: 210, name: 'Suriname', iso2: 'SR', translations: { de: 'Suriname' }, emoji: '🇸🇷' },
  {
    id: 211,
    name: 'Svalbard and Jan Mayen Islands',
    iso2: 'SJ',
    translations: { de: 'Svalbard und Jan Mayen' },
    emoji: '🇸🇯',
  },
  { id: 213, name: 'Sweden', iso2: 'SE', translations: { de: 'Schweden' }, emoji: '🇸🇪' },
  { id: 214, name: 'Switzerland', iso2: 'CH', translations: { de: 'Schweiz' }, emoji: '🇨🇭' },
  { id: 215, name: 'Syria', iso2: 'SY', translations: { de: 'Syrien' }, emoji: '🇸🇾' },
  { id: 216, name: 'Taiwan', iso2: 'TW', translations: { de: 'Taiwan' }, emoji: '🇹🇼' },
  { id: 217, name: 'Tajikistan', iso2: 'TJ', translations: { de: 'Tadschikistan' }, emoji: '🇹🇯' },
  { id: 218, name: 'Tanzania', iso2: 'TZ', translations: { de: 'Tansania' }, emoji: '🇹🇿' },
  { id: 219, name: 'Thailand', iso2: 'TH', translations: { de: 'Thailand' }, emoji: '🇹🇭' },
  { id: 17, name: 'The Bahamas', iso2: 'BS', translations: { de: 'Bahamas' }, emoji: '🇧🇸' },
  { id: 63, name: 'Timor-Leste', iso2: 'TL', translations: { de: 'Timor-Leste' }, emoji: '🇹🇱' },
  { id: 220, name: 'Togo', iso2: 'TG', translations: { de: 'Togo' }, emoji: '🇹🇬' },
  { id: 221, name: 'Tokelau', iso2: 'TK', translations: { de: 'Tokelau' }, emoji: '🇹🇰' },
  { id: 222, name: 'Tonga', iso2: 'TO', translations: { de: 'Tonga' }, emoji: '🇹🇴' },
  {
    id: 223,
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    translations: { de: 'Trinidad und Tobago' },
    emoji: '🇹🇹',
  },
  { id: 224, name: 'Tunisia', iso2: 'TN', translations: { de: 'Tunesien' }, emoji: '🇹🇳' },
  { id: 225, name: 'Turkey', iso2: 'TR', translations: { de: 'Türkei' }, emoji: '🇹🇷' },
  { id: 226, name: 'Turkmenistan', iso2: 'TM', translations: { de: 'Turkmenistan' }, emoji: '🇹🇲' },
  {
    id: 227,
    name: 'Turks and Caicos Islands',
    iso2: 'TC',
    translations: { de: 'Turks- und Caicosinseln' },
    emoji: '🇹🇨',
  },
  { id: 228, name: 'Tuvalu', iso2: 'TV', translations: { de: 'Tuvalu' }, emoji: '🇹🇻' },
  { id: 229, name: 'Uganda', iso2: 'UG', translations: { de: 'Uganda' }, emoji: '🇺🇬' },
  { id: 230, name: 'Ukraine', iso2: 'UA', translations: { de: 'Ukraine' }, emoji: '🇺🇦' },
  {
    id: 231,
    name: 'United Arab Emirates',
    iso2: 'AE',
    translations: { de: 'Vereinigte Arabische Emirate' },
    emoji: '🇦🇪',
  },
  {
    id: 232,
    name: 'United Kingdom',
    iso2: 'GB',
    translations: { de: 'Vereinigtes Königreich' },
    emoji: '🇬🇧',
  },
  {
    id: 233,
    name: 'United States',
    iso2: 'US',
    translations: { de: 'Vereinigte Staaten von Amerika' },
    emoji: '🇺🇸',
  },
  {
    id: 234,
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    translations: { de: 'Kleinere Inselbesitzungen der Vereinigten Staaten' },
    emoji: '🇺🇲',
  },
  { id: 235, name: 'Uruguay', iso2: 'UY', translations: { de: 'Uruguay' }, emoji: '🇺🇾' },
  { id: 236, name: 'Uzbekistan', iso2: 'UZ', translations: { de: 'Usbekistan' }, emoji: '🇺🇿' },
  { id: 237, name: 'Vanuatu', iso2: 'VU', translations: { de: 'Vanuatu' }, emoji: '🇻🇺' },
  {
    id: 238,
    name: 'Vatican City State (Holy See)',
    iso2: 'VA',
    translations: { de: 'Heiliger Stuhl' },
    emoji: '🇻🇦',
  },
  { id: 239, name: 'Venezuela', iso2: 'VE', translations: { de: 'Venezuela' }, emoji: '🇻🇪' },
  { id: 240, name: 'Vietnam', iso2: 'VN', translations: { de: 'Vietnam' }, emoji: '🇻🇳' },
  {
    id: 241,
    name: 'Virgin Islands (British)',
    iso2: 'VG',
    translations: { de: 'Britische Jungferninseln' },
    emoji: '🇻🇬',
  },
  {
    id: 242,
    name: 'Virgin Islands (US)',
    iso2: 'VI',
    translations: { de: 'Amerikanische Jungferninseln' },
    emoji: '🇻🇮',
  },
  {
    id: 243,
    name: 'Wallis and Futuna Islands',
    iso2: 'WF',
    translations: { de: 'Wallis und Futuna' },
    emoji: '🇼🇫',
  },
  { id: 244, name: 'Western Sahara', iso2: 'EH', translations: { de: 'Westsahara' }, emoji: '🇪🇭' },
  { id: 245, name: 'Yemen', iso2: 'YE', translations: { de: 'Jemen' }, emoji: '🇾🇪' },
  { id: 246, name: 'Zambia', iso2: 'ZM', translations: { de: 'Sambia' }, emoji: '🇿🇲' },
  { id: 247, name: 'Zimbabwe', iso2: 'ZW', translations: { de: 'Simbabwe' }, emoji: '🇿🇼' },
];
